### ISSUE TITLE
Can only pull last 250 days

### ISSUE THREAD

**Issue by tavurth** [apilayer/marketstack#11]
I'm on a free account, but even when using `&limit=1000` I'm not receiving more than 250 days of data.

**Comment by PavanKSurpaneni** [comment]
that's because free account has access to only 1 year of historical data

**Comment by tavurth** [comment]
Thanks for the update, is that then since EOY 2019? 

Perhaps it would prevent others asking this question if it would return 365 days, as that would clearly indicate free-user limitations.
