### ISSUE TITLE
DOCS: Historical Data Example 

### ISSUE THREAD

**Issue by edev2383** [apilayer/marketstack#2]
Unsure if it's a typo or a usage issue, but I got an error using the following example from Historical Data Example API Request

```
https://api.marketstack.com/v1/eod
    ? access_key = YOUR_ACCESS_KEY
    & symbol = AAPL
    & date_from = 2019-01-01
    & date_to = 2019-02-01
```

I had to change 'symbol' param to 'symbols' and it worked.

**Comment by paulzehetmayr** [comment]
done
