### ISSUE TITLE
Australian symbols

### ISSUE THREAD

**Issue by mikkelking** [apilayer/marketstack#3]
Hi, I used to use the worldtradedata api, and am adapting to use marketstack.

I am trying to get Australian stock exchange data, but nothing seems to work

If I ask for the tickers

http://api.marketstack.com/v1/tickers?access_key=MY-KEY&exchange=XASX
I get only 4 back

``` json
{"pagination":{"limit":100,"offset":0,"count":4,"total":4},"data":[{"name":null,"symbol":"ACB.XASX","stock_exchange":{"name":"Australia Stock Exchange","acronym":"ASX","mic":"XASX","country":"Australia","country_code":"AU","city":"New York","website":"www.asx.com.au","timezone":{"timezone":"Australia\/Sydney","abbr":"AEST","abbr_dst":"AEDT"}}},{"name":null,"symbol":"AUT.XASX","stock_exchange":{"name":"Australia Stock Exchange","acronym":"ASX","mic":"XASX","country":"Australia","country_code":"AU","city":"New York","website":"www.asx.com.au","timezone":{"timezone":"Australia\/Sydney","abbr":"AEST","abbr_dst":"AEDT"}}},{"name":null,"symbol":"BET.XASX","stock_exchange":{"name":"Australia Stock Exchange","acronym":"ASX","mic":"XASX","country":"Australia","country_code":"AU","city":"New York","website":"www.asx.com.au","timezone":{"timezone":"Australia\/Sydney","abbr":"AEST","abbr_dst":"AEDT"}}},{"name":null,"symbol":"PUA.XASX","stock_exchange":{"name":"Australia Stock Exchange","acronym":"ASX","mic":"XASX","country":"Australia","country_code":"AU","city":"New York","website":"www.asx.com.au","timezone":{"timezone":"Australia\/Sydney","abbr":"AEST","abbr_dst":"AEDT"}}}]}
```
If I then ask for one of these tickers, eg BET.XASX, then I get no data:

http://api.marketstack.com/v1/eod?access_key=MY-KEY&symbols=BET.ASX

``` json
{"pagination":{"limit":100,"offset":0,"count":0,"total":0},"data":[]}
```

Any ideas?

**Comment by hendorog** [comment]
I just signed up and I have the same issue with getting prices for ASX and NZX (New Zealand) symbols. Have not been able to get an eod or intraday prices for anything on these two exchanges no matter what I try.
e.g.
https://api.marketstack.com/v1/eod?access_key=KEY&symbols=RVX.XASX

https://api.marketstack.com/v1/eod?access_key=KEY&symbols=FPH.XNZE

FWIW, the first problem you mentioned does not seem to affect the NZX - i.e. listing the tickers only results in 4 from ASX whereas NZX shows what appears to be a full list.

**Comment by mikkelking** [comment]
It looks like they fixed it now :)
