### ISSUE TITLE
No data since 03 May 2023 for other exchanges than NASDAQ

### ISSUE THREAD

**Issue by VolkerDiehl** [apilayer/marketstack#36]
I use the market stack API layer and want to receive end of day data, for example with 

https://api/marketstack.com/v1/eod?symbols=BAS.XETRA&date_from=2023-01-01&access_key=xxx

but I got only data to the 03.05.2023. I try other sources and it seems only data from NASDAQ is up-to-date, not for XETRA and other exchanges.

**Comment by OliverGruenewald** [comment]
Hello, same for me here. Support said they are working on it. That was a week ago. I am very disappointed because I am paying money for this service and I have to rely on a working API.

**Comment by VolkerDiehl** [comment]
Still not working and no reaction.

**Comment by bwirt** [comment]
> Still not working and no reaction.

Seriously?  This is a paid product.  I think I will look elsewhere...

**Comment by VolkerDiehl** [comment]
It seems the issue is reolved, th data is available.
